GitHub-Campus-Club-PSGCT/cseaimlfirstyearworkshop-2025

- students/D25Z380.txt
> Its just my name, and.... nothing interesting, That's all

- students/D25Z337.txt
> i am dharunika

- students/D25Z359
> hello Github!

- students/D25Z339.txt
> I am SOWMIYA

- students/D25Z356.txt
> I am sudharsan <3

- students/D25Z351.txt
> sanjuth kumar

- students/D25Z385.txt
This is D25Z385 Leaning about GITHUB from PSG seniors
> GIT project D25Z385

- students/D25Z368.txt
> good morning

- students/D25Z377.txt
> I am shahilrehan

- students/D25Z321.txt
> / i am balaganga D25Z321

- students/D25Z347.txt
> I am Naruto Uzumakai

- students/D25Z344.txt
> I am subashree

- students/D25Z324.txt
> hello world

- students/D25Z334.txt
>  I am divyadharshini

- students/D25Z360.txt
> I am D25Z360

- students/D25Z322.txt
> Hello github ! Excited for new projects

- students/25Z373
> hello universe

- students/D25Z378.txt
> i am mouli

- students/D25Z383.txt
> I am 24n258

- students/D25Z305.txt
> I am Akshara

- students/D25Z346.txt
> I am Vengadesh
